import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import LowerNavbar from '@/components/Navbar_Lower';
import UpperNavbar from '@/components/Nabar';
// Import the Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] });

// Metadata for the application
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UpperNavbar/>
        <LowerNavbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
